module.exports = {
  apps: [
    {
      name: "divisas-backend",
      cwd: "./backend",
      script: "npm",
      args: "run start:dev",
      interpreter: "none",
      autorestart: true,
      watch: false,
    },
    {
      name: "divisas-admin",
      cwd: "./apps/admin",
      script: "npx",
      args: "next dev -H 0.0.0.0 -p 3001",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        BACKEND_INTERNAL_URL: "http://127.0.0.1:3000",
      },
    },
    {
      name: "divisas-cashier",
      cwd: "./apps/cashier",
      script: "npx",
      args: "next dev -H 0.0.0.0 -p 3002",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        BACKEND_INTERNAL_URL: "http://127.0.0.1:3000",
      },
    },
    {
      name: "divisas-tunnel-backend",
      script: "cloudflared",
      args: "tunnel --url http://localhost:3000",
      interpreter: "none",
      autorestart: true,
      watch: false,
    },
    {
      name: "divisas-tunnel-admin",
      script: "cloudflared",
      args: "tunnel --url http://localhost:3001",
      interpreter: "none",
      autorestart: true,
      watch: false,
    },
    {
      name: "divisas-tunnel-cashier",
      script: "cloudflared",
      args: "tunnel --url http://localhost:3002",
      interpreter: "none",
      autorestart: true,
      watch: false,
    },
  ],
};
